package com.rookies.ecommerceapi.entity;

public enum RoleName {
    ROLE_CUSTOMER, ROLE_EMPLOYEE, ROLE_MANAGER, ROLE_ADMIN, ROLE_CUSTOMER_LOCKED, ROLE_EMPLOYEE_LOCKED,
    ROLE_MANAGER_LOCKED, ROLE_ADMIN_LOCKED
}
